### ISSUE TITLE
Purpose of 'extract_cfa_feat'

### ISSUE THREAD

**Issue by KanghoonYoon** [HKUST-LongGroup/CFA#2]
Thank you for sharing your code. 

I am currently seeing the details of the code, I confirmed three options 'extract_cfa_feat', 'cfa', and 'extract_aug'.

---
'extract_aug' seems to save the roi features in the memory bank; 'cfa' is an option used to train motif-cfa.
But I can't see the use of 'extract_cfa_feat'.
---

Am I correctly understanding the function of each option? 
If I am wrong, can you explain the purpose of each option?

Thank you

**Comment by muktilin** [comment]
'extract_cfa_feat' is used to extract features trained by the cfa, and I visualized its t-sne plot during rebuttal, you can ignore this.

**Comment by KanghoonYoon** [comment]
Thank you :)
