### ISSUE TITLE
Regarding the input of Relation Feature Extractor for CFA

### ISSUE THREAD

**Issue by KanghoonYoon** [HKUST-LongGroup/CFA#3]
Hello.

I tried to run the python execution in the guidelines in your readme as follows:

```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port 10054 --nproc_per_node=2 tools/relation_train_net.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX True MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 2 DTYPE "float16" SOLVER.MAX_ITER 50000 SOLVER.VAL_PERIOD 2000 SOLVER.CHECKPOINT_PERIOD 2000 GLOVE_DIR glove MODEL.PRETRAINED_DETECTOR_CKPT checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR ./exp/motifs_cfa_sgcls TYPE cfa MIXUP.FEAT_PATH feats ``MIXUP.MIXUP_BG`` True ``MIXUP.MIXUP_FG True`` MIXUP.BG_LAMBDA 0.5 MIXUP.FG_LAMBDA 0.5 MIXUP.PREDICATE_LOSS_TYPE MIXUP_CE MIXUP.MIXUP_ADD_TAIL True FG_TAIL True FG_BODY True BG_TAIL True CL_TAIL True USE_PREDCLS_FEATURE False CONTRA True PKO False
```

However, I found that the feature extractor, **AugBilvlMxiUpRelationFeatureExtractor**, cannot get the MIX_UP_FG and MIX_UP_BG from the above command. I think the default of ``mix_up_fg`` and ``mix_up_bg`` is False (the forward function of AugBilvlMxiUpRelationFeatureExtractor), and your code does not put the ``cfg.MIX_UP_FG`` itself in the forward function of the relation feature extractor. So, when I run the code, the ``mix_up_fg`` and ``mix_up_bg`` are ``False`` although above command set these variables as ``True``

I think it needs to be corrected. are there things that I misunderstood?

**Comment by KanghoonYoon** [comment]
Sorry. I misunderstood the code. I saw the old_roi_features, so I closed my issue.

**Comment by muktilin** [comment]
In the Line 132 in relation_head.py, we set mix_up_fg and mix_up_bg to False to get the original roi features of the objects, which is utilized for the contrastive loss.  It is because that we just want to get original roi features of the objects. The cfg.MIX_UP_FG and cfg.MIX_UP_BG is utilized in Line 135 in relation_head.py to perform feature augmentation. So, there is no error in the code. If you have any other questions, please continue to contact me ^_^.
